<?php
namespace LCSNG\Tools\CountryData\Traits;

/**
 * Comprehensive country data array
 * Returns array of all countries with their details
 */
trait CountryData 
{
    public static function getAll() {
        return [
            // Africa
            [
                'name' => 'Algeria',
                'official_name' => 'People\'s Democratic Republic of Algeria',
                'common_name' => 'Algeria',
                'short_name' => 'Algeria',
                'iso2' => 'DZ',
                'iso3' => 'DZA',
                'calling_code' => 213,
                'calling_codes' => [213],
                'capital' => 'Algiers',
                'region' => 'Africa',
                'subregion' => 'Northern Africa'
            ],
            [
                'name' => 'Angola',
                'official_name' => 'Republic of Angola',
                'common_name' => 'Angola',
                'short_name' => 'Angola',
                'iso2' => 'AO',
                'iso3' => 'AGO',
                'calling_code' => 244,
                'calling_codes' => [244],
                'capital' => 'Luanda',
                'region' => 'Africa',
                'subregion' => 'Middle Africa'
            ],
            [
                'name' => 'Benin',
                'official_name' => 'Republic of Benin',
                'common_name' => 'Benin',
                'short_name' => 'Benin',
                'iso2' => 'BJ',
                'iso3' => 'BEN',
                'calling_code' => 229,
                'calling_codes' => [229],
                'capital' => 'Porto-Novo',
                'region' => 'Africa',
                'subregion' => 'Western Africa'
            ],
            [
                'name' => 'Botswana',
                'official_name' => 'Republic of Botswana',
                'common_name' => 'Botswana',
                'short_name' => 'Botswana',
                'iso2' => 'BW',
                'iso3' => 'BWA',
                'calling_code' => 267,
                'calling_codes' => [267],
                'capital' => 'Gaborone',
                'region' => 'Africa',
                'subregion' => 'Southern Africa'
            ],
            [
                'name' => 'Burkina Faso',
                'official_name' => 'Burkina Faso',
                'common_name' => 'Burkina Faso',
                'short_name' => 'Burkina Faso',
                'iso2' => 'BF',
                'iso3' => 'BFA',
                'calling_code' => 226,
                'calling_codes' => [226],
                'capital' => 'Ouagadougou',
                'region' => 'Africa',
                'subregion' => 'Western Africa'
            ],
            [
                'name' => 'Burundi',
                'official_name' => 'Republic of Burundi',
                'common_name' => 'Burundi',
                'short_name' => 'Burundi',
                'iso2' => 'BI',
                'iso3' => 'BDI',
                'calling_code' => 257,
                'calling_codes' => [257],
                'capital' => 'Gitega',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa'
            ],
            [
                'name' => 'Cabo Verde',
                'official_name' => 'Republic of Cabo Verde',
                'common_name' => 'Cape Verde',
                'short_name' => 'Cape Verde',
                'iso2' => 'CV',
                'iso3' => 'CPV',
                'calling_code' => 238,
                'calling_codes' => [238],
                'capital' => 'Praia',
                'region' => 'Africa',
                'subregion' => 'Western Africa'
            ],
            [
                'name' => 'Cameroon',
                'official_name' => 'Republic of Cameroon',
                'common_name' => 'Cameroon',
                'short_name' => 'Cameroon',
                'iso2' => 'CM',
                'iso3' => 'CMR',
                'calling_code' => 237,
                'calling_codes' => [237],
                'capital' => 'Yaoundé',
                'region' => 'Africa',
                'subregion' => 'Middle Africa'
            ],
            [
                'name' => 'Central African Republic',
                'official_name' => 'Central African Republic',
                'common_name' => 'Central African Republic',
                'short_name' => 'CAR',
                'iso2' => 'CF',
                'iso3' => 'CAF',
                'calling_code' => 236,
                'calling_codes' => [236],
                'capital' => 'Bangui',
                'region' => 'Africa',
                'subregion' => 'Middle Africa'
            ],
            [
                'name' => 'Chad',
                'official_name' => 'Republic of Chad',
                'common_name' => 'Chad',
                'short_name' => 'Chad',
                'iso2' => 'TD',
                'iso3' => 'TCD',
                'calling_code' => 235,
                'calling_codes' => [235],
                'capital' => 'N\'Djamena',
                'region' => 'Africa',
                'subregion' => 'Middle Africa'
            ],
            [
                'name' => 'Comoros',
                'official_name' => 'Union of the Comoros',
                'common_name' => 'Comoros',
                'short_name' => 'Comoros',
                'iso2' => 'KM',
                'iso3' => 'COM',
                'calling_code' => 269,
                'calling_codes' => [269],
                'capital' => 'Moroni',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa'
            ],
            [
                'name' => 'Congo',
                'official_name' => 'Republic of the Congo',
                'common_name' => 'Congo',
                'short_name' => 'Congo',
                'iso2' => 'CG',
                'iso3' => 'COG',
                'calling_code' => 242,
                'calling_codes' => [242],
                'capital' => 'Brazzaville',
                'region' => 'Africa',
                'subregion' => 'Middle Africa'
            ],
            [
                'name' => 'Democratic Republic of the Congo',
                'official_name' => 'Democratic Republic of the Congo',
                'common_name' => 'DR Congo',
                'short_name' => 'DRC',
                'iso2' => 'CD',
                'iso3' => 'COD',
                'calling_code' => 243,
                'calling_codes' => [243],
                'capital' => 'Kinshasa',
                'region' => 'Africa',
                'subregion' => 'Middle Africa'
            ],
            [
                'name' => 'Djibouti',
                'official_name' => 'Republic of Djibouti',
                'common_name' => 'Djibouti',
                'short_name' => 'Djibouti',
                'iso2' => 'DJ',
                'iso3' => 'DJI',
                'calling_code' => 253,
                'calling_codes' => [253],
                'capital' => 'Djibouti',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa'
            ],
            [
                'name' => 'Egypt',
                'official_name' => 'Arab Republic of Egypt',
                'common_name' => 'Egypt',
                'short_name' => 'Egypt',
                'iso2' => 'EG',
                'iso3' => 'EGY',
                'calling_code' => 20,
                'calling_codes' => [20],
                'capital' => 'Cairo',
                'region' => 'Africa',
                'subregion' => 'Northern Africa'
            ],
            [
                'name' => 'Equatorial Guinea',
                'official_name' => 'Republic of Equatorial Guinea',
                'common_name' => 'Equatorial Guinea',
                'short_name' => 'Eq. Guinea',
                'iso2' => 'GQ',
                'iso3' => 'GNQ',
                'calling_code' => 240,
                'calling_codes' => [240],
                'capital' => 'Malabo',
                'region' => 'Africa',
                'subregion' => 'Middle Africa'
            ],
            [
                'name' => 'Eritrea',
                'official_name' => 'State of Eritrea',
                'common_name' => 'Eritrea',
                'short_name' => 'Eritrea',
                'iso2' => 'ER',
                'iso3' => 'ERI',
                'calling_code' => 291,
                'calling_codes' => [291],
                'capital' => 'Asmara',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa'
            ],
            [
                'name' => 'Eswatini',
                'official_name' => 'Kingdom of Eswatini',
                'common_name' => 'Eswatini',
                'short_name' => 'Eswatini',
                'iso2' => 'SZ',
                'iso3' => 'SWZ',
                'calling_code' => 268,
                'calling_codes' => [268],
                'capital' => 'Mbabane',
                'region' => 'Africa',
                'subregion' => 'Southern Africa'
            ],
            [
                'name' => 'Ethiopia',
                'official_name' => 'Federal Democratic Republic of Ethiopia',
                'common_name' => 'Ethiopia',
                'short_name' => 'Ethiopia',
                'iso2' => 'ET',
                'iso3' => 'ETH',
                'calling_code' => 251,
                'calling_codes' => [251],
                'capital' => 'Addis Ababa',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa'
            ],
            [
                'name' => 'Gabon',
                'official_name' => 'Gabonese Republic',
                'common_name' => 'Gabon',
                'short_name' => 'Gabon',
                'iso2' => 'GA',
                'iso3' => 'GAB',
                'calling_code' => 241,
                'calling_codes' => [241],
                'capital' => 'Libreville',
                'region' => 'Africa',
                'subregion' => 'Middle Africa'
            ],
            [
                'name' => 'Gambia',
                'official_name' => 'Republic of the Gambia',
                'common_name' => 'Gambia',
                'short_name' => 'Gambia',
                'iso2' => 'GM',
                'iso3' => 'GMB',
                'calling_code' => 220,
                'calling_codes' => [220],
                'capital' => 'Banjul',
                'region' => 'Africa',
                'subregion' => 'Western Africa'
            ],
            [
                'name' => 'Ghana',
                'official_name' => 'Republic of Ghana',
                'common_name' => 'Ghana',
                'short_name' => 'Ghana',
                'iso2' => 'GH',
                'iso3' => 'GHA',
                'calling_code' => 233,
                'calling_codes' => [233],
                'capital' => 'Accra',
                'region' => 'Africa',
                'subregion' => 'Western Africa'
            ],
            [
                'name' => 'Guinea',
                'official_name' => 'Republic of Guinea',
                'common_name' => 'Guinea',
                'short_name' => 'Guinea',
                'iso2' => 'GN',
                'iso3' => 'GIN',
                'calling_code' => 224,
                'calling_codes' => [224],
                'capital' => 'Conakry',
                'region' => 'Africa',
                'subregion' => 'Western Africa'
            ],
            [
                'name' => 'Guinea-Bissau',
                'official_name' => 'Republic of Guinea-Bissau',
                'common_name' => 'Guinea-Bissau',
                'short_name' => 'Guinea-Bissau',
                'iso2' => 'GW',
                'iso3' => 'GNB',
                'calling_code' => 245,
                'calling_codes' => [245],
                'capital' => 'Bissau',
                'region' => 'Africa',
                'subregion' => 'Western Africa'
            ],
            [
                'name' => 'Ivory Coast',
                'official_name' => 'Republic of Côte d\'Ivoire',
                'common_name' => 'Ivory Coast',
                'short_name' => 'Ivory Coast',
                'iso2' => 'CI',
                'iso3' => 'CIV',
                'calling_code' => 225,
                'calling_codes' => [225],
                'capital' => 'Yamoussoukro',
                'region' => 'Africa',
                'subregion' => 'Western Africa'
            ],
            [
                'name' => 'Kenya',
                'official_name' => 'Republic of Kenya',
                'common_name' => 'Kenya',
                'short_name' => 'Kenya',
                'iso2' => 'KE',
                'iso3' => 'KEN',
                'calling_code' => 254,
                'calling_codes' => [254],
                'capital' => 'Nairobi',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa'
            ],
            [
                'name' => 'Lesotho',
                'official_name' => 'Kingdom of Lesotho',
                'common_name' => 'Lesotho',
                'short_name' => 'Lesotho',
                'iso2' => 'LS',
                'iso3' => 'LSO',
                'calling_code' => 266,
                'calling_codes' => [266],
                'capital' => 'Maseru',
                'region' => 'Africa',
                'subregion' => 'Southern Africa'
            ],
            [
                'name' => 'Liberia',
                'official_name' => 'Republic of Liberia',
                'common_name' => 'Liberia',
                'short_name' => 'Liberia',
                'iso2' => 'LR',
                'iso3' => 'LBR',
                'calling_code' => 231,
                'calling_codes' => [231],
                'capital' => 'Monrovia',
                'region' => 'Africa',
                'subregion' => 'Western Africa'
            ],
            [
                'name' => 'Libya',
                'official_name' => 'State of Libya',
                'common_name' => 'Libya',
                'short_name' => 'Libya',
                'iso2' => 'LY',
                'iso3' => 'LBY',
                'calling_code' => 218,
                'calling_codes' => [218],
                'capital' => 'Tripoli',
                'region' => 'Africa',
                'subregion' => 'Northern Africa'
            ],
            [
                'name' => 'Madagascar',
                'official_name' => 'Republic of Madagascar',
                'common_name' => 'Madagascar',
                'short_name' => 'Madagascar',
                'iso2' => 'MG',
                'iso3' => 'MDG',
                'calling_code' => 261,
                'calling_codes' => [261],
                'capital' => 'Antananarivo',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa'
            ],
            [
                'name' => 'Malawi',
                'official_name' => 'Republic of Malawi',
                'common_name' => 'Malawi',
                'short_name' => 'Malawi',
                'iso2' => 'MW',
                'iso3' => 'MWI',
                'calling_code' => 265,
                'calling_codes' => [265],
                'capital' => 'Lilongwe',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa'
            ],
            [
                'name' => 'Mali',
                'official_name' => 'Republic of Mali',
                'common_name' => 'Mali',
                'short_name' => 'Mali',
                'iso2' => 'ML',
                'iso3' => 'MLI',
                'calling_code' => 223,
                'calling_codes' => [223],
                'capital' => 'Bamako',
                'region' => 'Africa',
                'subregion' => 'Western Africa'
            ],
            [
                'name' => 'Mauritania',
                'official_name' => 'Islamic Republic of Mauritania',
                'common_name' => 'Mauritania',
                'short_name' => 'Mauritania',
                'iso2' => 'MR',
                'iso3' => 'MRT',
                'calling_code' => 222,
                'calling_codes' => [222],
                'capital' => 'Nouakchott',
                'region' => 'Africa',
                'subregion' => 'Western Africa'
            ],
            [
                'name' => 'Mauritius',
                'official_name' => 'Republic of Mauritius',
                'common_name' => 'Mauritius',
                'short_name' => 'Mauritius',
                'iso2' => 'MU',
                'iso3' => 'MUS',
                'calling_code' => 230,
                'calling_codes' => [230],
                'capital' => 'Port Louis',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa'
            ],
            [
                'name' => 'Morocco',
                'official_name' => 'Kingdom of Morocco',
                'common_name' => 'Morocco',
                'short_name' => 'Morocco',
                'iso2' => 'MA',
                'iso3' => 'MAR',
                'calling_code' => 212,
                'calling_codes' => [212],
                'capital' => 'Rabat',
                'region' => 'Africa',
                'subregion' => 'Northern Africa'
            ],
            [
                'name' => 'Mozambique',
                'official_name' => 'Republic of Mozambique',
                'common_name' => 'Mozambique',
                'short_name' => 'Mozambique',
                'iso2' => 'MZ',
                'iso3' => 'MOZ',
                'calling_code' => 258,
                'calling_codes' => [258],
                'capital' => 'Maputo',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa'
            ],
            [
                'name' => 'Namibia',
                'official_name' => 'Republic of Namibia',
                'common_name' => 'Namibia',
                'short_name' => 'Namibia',
                'iso2' => 'NA',
                'iso3' => 'NAM',
                'calling_code' => 264,
                'calling_codes' => [264],
                'capital' => 'Windhoek',
                'region' => 'Africa',
                'subregion' => 'Southern Africa'
            ],
            [
                'name' => 'Niger',
                'official_name' => 'Republic of Niger',
                'common_name' => 'Niger',
                'short_name' => 'Niger',
                'iso2' => 'NE',
                'iso3' => 'NER',
                'calling_code' => 227,
                'calling_codes' => [227],
                'capital' => 'Niamey',
                'region' => 'Africa',
                'subregion' => 'Western Africa'
            ],
            [
                'name' => 'Nigeria',
                'official_name' => 'Federal Republic of Nigeria',
                'common_name' => 'Nigeria',
                'short_name' => 'Nigeria',
                'iso2' => 'NG',
                'iso3' => 'NGA',
                'calling_code' => 234,
                'calling_codes' => [234],
                'capital' => 'Abuja',
                'region' => 'Africa',
                'subregion' => 'Western Africa'
            ],
            [
                'name' => 'Rwanda',
                'official_name' => 'Republic of Rwanda',
                'common_name' => 'Rwanda',
                'short_name' => 'Rwanda',
                'iso2' => 'RW',
                'iso3' => 'RWA',
                'calling_code' => 250,
                'calling_codes' => [250],
                'capital' => 'Kigali',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa'
            ],
            [
                'name' => 'São Tomé and Príncipe',
                'official_name' => 'Democratic Republic of São Tomé and Príncipe',
                'common_name' => 'São Tomé and Príncipe',
                'short_name' => 'São Tomé',
                'iso2' => 'ST',
                'iso3' => 'STP',
                'calling_code' => 239,
                'calling_codes' => [239],
                'capital' => 'São Tomé',
                'region' => 'Africa',
                'subregion' => 'Middle Africa'
            ],
            [
                'name' => 'Senegal',
                'official_name' => 'Republic of Senegal',
                'common_name' => 'Senegal',
                'short_name' => 'Senegal',
                'iso2' => 'SN',
                'iso3' => 'SEN',
                'calling_code' => 221,
                'calling_codes' => [221],
                'capital' => 'Dakar',
                'region' => 'Africa',
                'subregion' => 'Western Africa'
            ],
            [
                'name' => 'Seychelles',
                'official_name' => 'Republic of Seychelles',
                'common_name' => 'Seychelles',
                'short_name' => 'Seychelles',
                'iso2' => 'SC',
                'iso3' => 'SYC',
                'calling_code' => 248,
                'calling_codes' => [248],
                'capital' => 'Victoria',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa'
            ],
            [
                'name' => 'Sierra Leone',
                'official_name' => 'Republic of Sierra Leone',
                'common_name' => 'Sierra Leone',
                'short_name' => 'Sierra Leone',
                'iso2' => 'SL',
                'iso3' => 'SLE',
                'calling_code' => 232,
                'calling_codes' => [232],
                'capital' => 'Freetown',
                'region' => 'Africa',
                'subregion' => 'Western Africa'
            ],
            [
                'name' => 'Somalia',
                'official_name' => 'Federal Republic of Somalia',
                'common_name' => 'Somalia',
                'short_name' => 'Somalia',
                'iso2' => 'SO',
                'iso3' => 'SOM',
                'calling_code' => 252,
                'calling_codes' => [252],
                'capital' => 'Mogadishu',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa'
            ],
            [
                'name' => 'South Africa',
                'official_name' => 'Republic of South Africa',
                'common_name' => 'South Africa',
                'short_name' => 'South Africa',
                'iso2' => 'ZA',
                'iso3' => 'ZAF',
                'calling_code' => 27,
                'calling_codes' => [27],
                'capital' => 'Pretoria',
                'region' => 'Africa',
                'subregion' => 'Southern Africa'
            ],
            [
                'name' => 'South Sudan',
                'official_name' => 'Republic of South Sudan',
                'common_name' => 'South Sudan',
                'short_name' => 'South Sudan',
                'iso2' => 'SS',
                'iso3' => 'SSD',
                'calling_code' => 211,
                'calling_codes' => [211],
                'capital' => 'Juba',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa'
            ],
            [
                'name' => 'Sudan',
                'official_name' => 'Republic of the Sudan',
                'common_name' => 'Sudan',
                'short_name' => 'Sudan',
                'iso2' => 'SD',
                'iso3' => 'SDN',
                'calling_code' => 249,
                'calling_codes' => [249],
                'capital' => 'Khartoum',
                'region' => 'Africa',
                'subregion' => 'Northern Africa'
            ],
            [
                'name' => 'Tanzania',
                'official_name' => 'United Republic of Tanzania',
                'common_name' => 'Tanzania',
                'short_name' => 'Tanzania',
                'iso2' => 'TZ',
                'iso3' => 'TZA',
                'calling_code' => 255,
                'calling_codes' => [255],
                'capital' => 'Dodoma',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa'
            ],
            [
                'name' => 'Togo',
                'official_name' => 'Togolese Republic',
                'common_name' => 'Togo',
                'short_name' => 'Togo',
                'iso2' => 'TG',
                'iso3' => 'TGO',
                'calling_code' => 228,
                'calling_codes' => [228],
                'capital' => 'Lomé',
                'region' => 'Africa',
                'subregion' => 'Western Africa'
            ],
            [
                'name' => 'Tunisia',
                'official_name' => 'Republic of Tunisia',
                'common_name' => 'Tunisia',
                'short_name' => 'Tunisia',
                'iso2' => 'TN',
                'iso3' => 'TUN',
                'calling_code' => 216,
                'calling_codes' => [216],
                'capital' => 'Tunis',
                'region' => 'Africa',
                'subregion' => 'Northern Africa'
            ],
            [
                'name' => 'Uganda',
                'official_name' => 'Republic of Uganda',
                'common_name' => 'Uganda',
                'short_name' => 'Uganda',
                'iso2' => 'UG',
                'iso3' => 'UGA',
                'calling_code' => 256,
                'calling_codes' => [256],
                'capital' => 'Kampala',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa'
            ],
            [
                'name' => 'Zambia',
                'official_name' => 'Republic of Zambia',
                'common_name' => 'Zambia',
                'short_name' => 'Zambia',
                'iso2' => 'ZM',
                'iso3' => 'ZMB',
                'calling_code' => 260,
                'calling_codes' => [260],
                'capital' => 'Lusaka',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa'
            ],
            [
                'name' => 'Zimbabwe',
                'official_name' => 'Republic of Zimbabwe',
                'common_name' => 'Zimbabwe',
                'short_name' => 'Zimbabwe',
                'iso2' => 'ZW',
                'iso3' => 'ZWE',
                'calling_code' => 263,
                'calling_codes' => [263],
                'capital' => 'Harare',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa'
            ],

            // Americas
            [
                'name' => 'Antigua and Barbuda',
                'official_name' => 'Antigua and Barbuda',
                'common_name' => 'Antigua and Barbuda',
                'short_name' => 'Antigua',
                'iso2' => 'AG',
                'iso3' => 'ATG',
                'calling_code' => 1268,
                'calling_codes' => [1268],
                'capital' => 'Saint John\'s',
                'region' => 'Americas',
                'subregion' => 'Caribbean'
            ],
            [
                'name' => 'Argentina',
                'official_name' => 'Argentine Republic',
                'common_name' => 'Argentina',
                'short_name' => 'Argentina',
                'iso2' => 'AR',
                'iso3' => 'ARG',
                'calling_code' => 54,
                'calling_codes' => [54],
                'capital' => 'Buenos Aires',
                'region' => 'Americas',
                'subregion' => 'South America'
            ],
            [
                'name' => 'Bahamas',
                'official_name' => 'Commonwealth of the Bahamas',
                'common_name' => 'Bahamas',
                'short_name' => 'Bahamas',
                'iso2' => 'BS',
                'iso3' => 'BHS',
                'calling_code' => 1242,
                'calling_codes' => [1242],
                'capital' => 'Nassau',
                'region' => 'Americas',
                'subregion' => 'Caribbean'
            ],
            [
                'name' => 'Barbados',
                'official_name' => 'Barbados',
                'common_name' => 'Barbados',
                'short_name' => 'Barbados',
                'iso2' => 'BB',
                'iso3' => 'BRB',
                'calling_code' => 1246,
                'calling_codes' => [1246],
                'capital' => 'Bridgetown',
                'region' => 'Americas',
                'subregion' => 'Caribbean'
            ],
            [
                'name' => 'Belize',
                'official_name' => 'Belize',
                'common_name' => 'Belize',
                'short_name' => 'Belize',
                'iso2' => 'BZ',
                'iso3' => 'BLZ',
                'calling_code' => 501,
                'calling_codes' => [501],
                'capital' => 'Belmopan',
                'region' => 'Americas',
                'subregion' => 'Central America'
            ],
            [
                'name' => 'Bolivia',
                'official_name' => 'Plurinational State of Bolivia',
                'common_name' => 'Bolivia',
                'short_name' => 'Bolivia',
                'iso2' => 'BO',
                'iso3' => 'BOL',
                'calling_code' => 591,
                'calling_codes' => [591],
                'capital' => 'Sucre',
                'region' => 'Americas',
                'subregion' => 'South America'
            ],
            [
                'name' => 'Brazil',
                'official_name' => 'Federative Republic of Brazil',
                'common_name' => 'Brazil',
                'short_name' => 'Brazil',
                'iso2' => 'BR',
                'iso3' => 'BRA',
                'calling_code' => 55,
                'calling_codes' => [55],
                'capital' => 'Brasília',
                'region' => 'Americas',
                'subregion' => 'South America'
            ],
            [
                'name' => 'Canada',
                'official_name' => 'Canada',
                'common_name' => 'Canada',
                'short_name' => 'Canada',
                'iso2' => 'CA',
                'iso3' => 'CAN',
                'calling_code' => 1,
                'calling_codes' => [1],
                'capital' => 'Ottawa',
                'region' => 'Americas',
                'subregion' => 'Northern America'
            ],
            [
                'name' => 'Chile',
                'official_name' => 'Republic of Chile',
                'common_name' => 'Chile',
                'short_name' => 'Chile',
                'iso2' => 'CL',
                'iso3' => 'CHL',
                'calling_code' => 56,
                'calling_codes' => [56],
                'capital' => 'Santiago',
                'region' => 'Americas',
                'subregion' => 'South America'
            ],
            [
                'name' => 'Colombia',
                'official_name' => 'Republic of Colombia',
                'common_name' => 'Colombia',
                'short_name' => 'Colombia',
                'iso2' => 'CO',
                'iso3' => 'COL',
                'calling_code' => 57,
                'calling_codes' => [57],
                'capital' => 'Bogotá',
                'region' => 'Americas',
                'subregion' => 'South America'
            ],
            [
                'name' => 'Costa Rica',
                'official_name' => 'Republic of Costa Rica',
                'common_name' => 'Costa Rica',
                'short_name' => 'Costa Rica',
                'iso2' => 'CR',
                'iso3' => 'CRI',
                'calling_code' => 506,
                'calling_codes' => [506],
                'capital' => 'San José',
                'region' => 'Americas',
                'subregion' => 'Central America'
            ],
            [
                'name' => 'Cuba',
                'official_name' => 'Republic of Cuba',
                'common_name' => 'Cuba',
                'short_name' => 'Cuba',
                'iso2' => 'CU',
                'iso3' => 'CUB',
                'calling_code' => 53,
                'calling_codes' => [53],
                'capital' => 'Havana',
                'region' => 'Americas',
                'subregion' => 'Caribbean'
            ],
            [
                'name' => 'Dominica',
                'official_name' => 'Commonwealth of Dominica',
                'common_name' => 'Dominica',
                'short_name' => 'Dominica',
                'iso2' => 'DM',
                'iso3' => 'DMA',
                'calling_code' => 1767,
                'calling_codes' => [1767],
                'capital' => 'Roseau',
                'region' => 'Americas',
                'subregion' => 'Caribbean'
            ],
            [
                'name' => 'Dominican Republic',
                'official_name' => 'Dominican Republic',
                'common_name' => 'Dominican Republic',
                'short_name' => 'Dominican Rep.',
                'iso2' => 'DO',
                'iso3' => 'DOM',
                'calling_code' => 1809,
                'calling_codes' => [1809, 1829, 1849],
                'capital' => 'Santo Domingo',
                'region' => 'Americas',
                'subregion' => 'Caribbean'
            ],
            [
                'name' => 'Ecuador',
                'official_name' => 'Republic of Ecuador',
                'common_name' => 'Ecuador',
                'short_name' => 'Ecuador',
                'iso2' => 'EC',
                'iso3' => 'ECU',
                'calling_code' => 593,
                'calling_codes' => [593],
                'capital' => 'Quito',
                'region' => 'Americas',
                'subregion' => 'South America'
            ],
            [
                'name' => 'El Salvador',
                'official_name' => 'Republic of El Salvador',
                'common_name' => 'El Salvador',
                'short_name' => 'El Salvador',
                'iso2' => 'SV',
                'iso3' => 'SLV',
                'calling_code' => 503,
                'calling_codes' => [503],
                'capital' => 'San Salvador',
                'region' => 'Americas',
                'subregion' => 'Central America'
            ],
            [
                'name' => 'Grenada',
                'official_name' => 'Grenada',
                'common_name' => 'Grenada',
                'short_name' => 'Grenada',
                'iso2' => 'GD',
                'iso3' => 'GRD',
                'calling_code' => 1473,
                'calling_codes' => [1473],
                'capital' => 'St. George\'s',
                'region' => 'Americas',
                'subregion' => 'Caribbean'
            ],
            [
                'name' => 'Guatemala',
                'official_name' => 'Republic of Guatemala',
                'common_name' => 'Guatemala',
                'short_name' => 'Guatemala',
                'iso2' => 'GT',
                'iso3' => 'GTM',
                'calling_code' => 502,
                'calling_codes' => [502],
                'capital' => 'Guatemala City',
                'region' => 'Americas',
                'subregion' => 'Central America'
            ],
            [
                'name' => 'Guyana',
                'official_name' => 'Co-operative Republic of Guyana',
                'common_name' => 'Guyana',
                'short_name' => 'Guyana',
                'iso2' => 'GY',
                'iso3' => 'GUY',
                'calling_code' => 592,
                'calling_codes' => [592],
                'capital' => 'Georgetown',
                'region' => 'Americas',
                'subregion' => 'South America'
            ],
            [
                'name' => 'Haiti',
                'official_name' => 'Republic of Haiti',
                'common_name' => 'Haiti',
                'short_name' => 'Haiti',
                'iso2' => 'HT',
                'iso3' => 'HTI',
                'calling_code' => 509,
                'calling_codes' => [509],
                'capital' => 'Port-au-Prince',
                'region' => 'Americas',
                'subregion' => 'Caribbean'
            ],
            [
                'name' => 'Honduras',
                'official_name' => 'Republic of Honduras',
                'common_name' => 'Honduras',
                'short_name' => 'Honduras',
                'iso2' => 'HN',
                'iso3' => 'HND',
                'calling_code' => 504,
                'calling_codes' => [504],
                'capital' => 'Tegucigalpa',
                'region' => 'Americas',
                'subregion' => 'Central America'
            ],
            [
                'name' => 'Jamaica',
                'official_name' => 'Jamaica',
                'common_name' => 'Jamaica',
                'short_name' => 'Jamaica',
                'iso2' => 'JM',
                'iso3' => 'JAM',
                'calling_code' => 1876,
                'calling_codes' => [1876],
                'capital' => 'Kingston',
                'region' => 'Americas',
                'subregion' => 'Caribbean'
            ],
            [
                'name' => 'Mexico',
                'official_name' => 'United Mexican States',
                'common_name' => 'Mexico',
                'short_name' => 'Mexico',
                'iso2' => 'MX',
                'iso3' => 'MEX',
                'calling_code' => 52,
                'calling_codes' => [52],
                'capital' => 'Mexico City',
                'region' => 'Americas',
                'subregion' => 'Central America'
            ],
            [
                'name' => 'Nicaragua',
                'official_name' => 'Republic of Nicaragua',
                'common_name' => 'Nicaragua',
                'short_name' => 'Nicaragua',
                'iso2' => 'NI',
                'iso3' => 'NIC',
                'calling_code' => 505,
                'calling_codes' => [505],
                'capital' => 'Managua',
                'region' => 'Americas',
                'subregion' => 'Central America'
            ],
            [
                'name' => 'Panama',
                'official_name' => 'Republic of Panama',
                'common_name' => 'Panama',
                'short_name' => 'Panama',
                'iso2' => 'PA',
                'iso3' => 'PAN',
                'calling_code' => 507,
                'calling_codes' => [507],
                'capital' => 'Panama City',
                'region' => 'Americas',
                'subregion' => 'Central America'
            ],
            [
                'name' => 'Paraguay',
                'official_name' => 'Republic of Paraguay',
                'common_name' => 'Paraguay',
                'short_name' => 'Paraguay',
                'iso2' => 'PY',
                'iso3' => 'PRY',
                'calling_code' => 595,
                'calling_codes' => [595],
                'capital' => 'Asunción',
                'region' => 'Americas',
                'subregion' => 'South America'
            ],
            [
                'name' => 'Peru',
                'official_name' => 'Republic of Peru',
                'common_name' => 'Peru',
                'short_name' => 'Peru',
                'iso2' => 'PE',
                'iso3' => 'PER',
                'calling_code' => 51,
                'calling_codes' => [51],
                'capital' => 'Lima',
                'region' => 'Americas',
                'subregion' => 'South America'
            ],
            [
                'name' => 'Saint Kitts and Nevis',
                'official_name' => 'Federation of Saint Christopher and Nevis',
                'common_name' => 'Saint Kitts and Nevis',
                'short_name' => 'St. Kitts',
                'iso2' => 'KN',
                'iso3' => 'KNA',
                'calling_code' => 1869,
                'calling_codes' => [1869],
                'capital' => 'Basseterre',
                'region' => 'Americas',
                'subregion' => 'Caribbean'
            ],
            [
                'name' => 'Saint Lucia',
                'official_name' => 'Saint Lucia',
                'common_name' => 'Saint Lucia',
                'short_name' => 'St. Lucia',
                'iso2' => 'LC',
                'iso3' => 'LCA',
                'calling_code' => 1758,
                'calling_codes' => [1758],
                'capital' => 'Castries',
                'region' => 'Americas',
                'subregion' => 'Caribbean'
            ],
            [
                'name' => 'Saint Vincent and the Grenadines',
                'official_name' => 'Saint Vincent and the Grenadines',
                'common_name' => 'Saint Vincent',
                'short_name' => 'St. Vincent',
                'iso2' => 'VC',
                'iso3' => 'VCT',
                'calling_code' => 1784,
                'calling_codes' => [1784],
                'capital' => 'Kingstown',
                'region' => 'Americas',
                'subregion' => 'Caribbean'
            ],
            [
                'name' => 'Suriname',
                'official_name' => 'Republic of Suriname',
                'common_name' => 'Suriname',
                'short_name' => 'Suriname',
                'iso2' => 'SR',
                'iso3' => 'SUR',
                'calling_code' => 597,
                'calling_codes' => [597],
                'capital' => 'Paramaribo',
                'region' => 'Americas',
                'subregion' => 'South America'
            ],
            [
                'name' => 'Trinidad and Tobago',
                'official_name' => 'Republic of Trinidad and Tobago',
                'common_name' => 'Trinidad and Tobago',
                'short_name' => 'Trinidad',
                'iso2' => 'TT',
                'iso3' => 'TTO',
                'calling_code' => 1868,
                'calling_codes' => [1868],
                'capital' => 'Port of Spain',
                'region' => 'Americas',
                'subregion' => 'Caribbean'
            ],
            [
                'name' => 'United States',
                'official_name' => 'United States of America',
                'common_name' => 'United States',
                'short_name' => 'USA',
                'iso2' => 'US',
                'iso3' => 'USA',
                'calling_code' => 1,
                'calling_codes' => [1],
                'capital' => 'Washington, D.C.',
                'region' => 'Americas',
                'subregion' => 'Northern America'
            ],
            [
                'name' => 'Uruguay',
                'official_name' => 'Oriental Republic of Uruguay',
                'common_name' => 'Uruguay',
                'short_name' => 'Uruguay',
                'iso2' => 'UY',
                'iso3' => 'URY',
                'calling_code' => 598,
                'calling_codes' => [598],
                'capital' => 'Montevideo',
                'region' => 'Americas',
                'subregion' => 'South America'
            ],
            [
                'name' => 'Venezuela',
                'official_name' => 'Bolivarian Republic of Venezuela',
                'common_name' => 'Venezuela',
                'short_name' => 'Venezuela',
                'iso2' => 'VE',
                'iso3' => 'VEN',
                'calling_code' => 58,
                'calling_codes' => [58],
                'capital' => 'Caracas',
                'region' => 'Americas',
                'subregion' => 'South America'
            ],

            // Asia
            [
                'name' => 'Afghanistan',
                'official_name' => 'Islamic Emirate of Afghanistan',
                'common_name' => 'Afghanistan',
                'short_name' => 'Afghanistan',
                'iso2' => 'AF',
                'iso3' => 'AFG',
                'calling_code' => 93,
                'calling_codes' => [93],
                'capital' => 'Kabul',
                'region' => 'Asia',
                'subregion' => 'Southern Asia'
            ],
            [
                'name' => 'Armenia',
                'official_name' => 'Republic of Armenia',
                'common_name' => 'Armenia',
                'short_name' => 'Armenia',
                'iso2' => 'AM',
                'iso3' => 'ARM',
                'calling_code' => 374,
                'calling_codes' => [374],
                'capital' => 'Yerevan',
                'region' => 'Asia',
                'subregion' => 'Western Asia'
            ],
            [
                'name' => 'Azerbaijan',
                'official_name' => 'Republic of Azerbaijan',
                'common_name' => 'Azerbaijan',
                'short_name' => 'Azerbaijan',
                'iso2' => 'AZ',
                'iso3' => 'AZE',
                'calling_code' => 994,
                'calling_codes' => [994],
                'capital' => 'Baku',
                'region' => 'Asia',
                'subregion' => 'Western Asia'
            ],
            [
                'name' => 'Bahrain',
                'official_name' => 'Kingdom of Bahrain',
                'common_name' => 'Bahrain',
                'short_name' => 'Bahrain',
                'iso2' => 'BH',
                'iso3' => 'BHR',
                'calling_code' => 973,
                'calling_codes' => [973],
                'capital' => 'Manama',
                'region' => 'Asia',
                'subregion' => 'Western Asia'
            ],
            [
                'name' => 'Bangladesh',
                'official_name' => 'People\'s Republic of Bangladesh',
                'common_name' => 'Bangladesh',
                'short_name' => 'Bangladesh',
                'iso2' => 'BD',
                'iso3' => 'BGD',
                'calling_code' => 880,
                'calling_codes' => [880],
                'capital' => 'Dhaka',
                'region' => 'Asia',
                'subregion' => 'Southern Asia'
            ],
            [
                'name' => 'Bhutan',
                'official_name' => 'Kingdom of Bhutan',
                'common_name' => 'Bhutan',
                'short_name' => 'Bhutan',
                'iso2' => 'BT',
                'iso3' => 'BTN',
                'calling_code' => 975,
                'calling_codes' => [975],
                'capital' => 'Thimphu',
                'region' => 'Asia',
                'subregion' => 'Southern Asia'
            ],
            [
                'name' => 'Brunei',
                'official_name' => 'Nation of Brunei, Abode of Peace',
                'common_name' => 'Brunei',
                'short_name' => 'Brunei',
                'iso2' => 'BN',
                'iso3' => 'BRN',
                'calling_code' => 673,
                'calling_codes' => [673],
                'capital' => 'Bandar Seri Begawan',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia'
            ],
            [
                'name' => 'Cambodia',
                'official_name' => 'Kingdom of Cambodia',
                'common_name' => 'Cambodia',
                'short_name' => 'Cambodia',
                'iso2' => 'KH',
                'iso3' => 'KHM',
                'calling_code' => 855,
                'calling_codes' => [855],
                'capital' => 'Phnom Penh',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia'
            ],
            [
                'name' => 'China',
                'official_name' => 'People\'s Republic of China',
                'common_name' => 'China',
                'short_name' => 'China',
                'iso2' => 'CN',
                'iso3' => 'CHN',
                'calling_code' => 86,
                'calling_codes' => [86],
                'capital' => 'Beijing',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia'
            ],
            [
                'name' => 'Cyprus',
                'official_name' => 'Republic of Cyprus',
                'common_name' => 'Cyprus',
                'short_name' => 'Cyprus',
                'iso2' => 'CY',
                'iso3' => 'CYP',
                'calling_code' => 357,
                'calling_codes' => [357],
                'capital' => 'Nicosia',
                'region' => 'Asia',
                'subregion' => 'Western Asia'
            ],
            [
                'name' => 'Georgia',
                'official_name' => 'Georgia',
                'common_name' => 'Georgia',
                'short_name' => 'Georgia',
                'iso2' => 'GE',
                'iso3' => 'GEO',
                'calling_code' => 995,
                'calling_codes' => [995],
                'capital' => 'Tbilisi',
                'region' => 'Asia',
                'subregion' => 'Western Asia'
            ],
            [
                'name' => 'India',
                'official_name' => 'Republic of India',
                'common_name' => 'India',
                'short_name' => 'India',
                'iso2' => 'IN',
                'iso3' => 'IND',
                'calling_code' => 91,
                'calling_codes' => [91],
                'capital' => 'New Delhi',
                'region' => 'Asia',
                'subregion' => 'Southern Asia'
            ],
            [
                'name' => 'Indonesia',
                'official_name' => 'Republic of Indonesia',
                'common_name' => 'Indonesia',
                'short_name' => 'Indonesia',
                'iso2' => 'ID',
                'iso3' => 'IDN',
                'calling_code' => 62,
                'calling_codes' => [62],
                'capital' => 'Jakarta',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia'
            ],
            [
                'name' => 'Iran',
                'official_name' => 'Islamic Republic of Iran',
                'common_name' => 'Iran',
                'short_name' => 'Iran',
                'iso2' => 'IR',
                'iso3' => 'IRN',
                'calling_code' => 98,
                'calling_codes' => [98],
                'capital' => 'Tehran',
                'region' => 'Asia',
                'subregion' => 'Southern Asia'
            ],
            [
                'name' => 'Iraq',
                'official_name' => 'Republic of Iraq',
                'common_name' => 'Iraq',
                'short_name' => 'Iraq',
                'iso2' => 'IQ',
                'iso3' => 'IRQ',
                'calling_code' => 964,
                'calling_codes' => [964],
                'capital' => 'Baghdad',
                'region' => 'Asia',
                'subregion' => 'Western Asia'
            ],
            [
                'name' => 'Israel',
                'official_name' => 'State of Israel',
                'common_name' => 'Israel',
                'short_name' => 'Israel',
                'iso2' => 'IL',
                'iso3' => 'ISR',
                'calling_code' => 972,
                'calling_codes' => [972],
                'capital' => 'Jerusalem',
                'region' => 'Asia',
                'subregion' => 'Western Asia'
            ],
            [
                'name' => 'Japan',
                'official_name' => 'Japan',
                'common_name' => 'Japan',
                'short_name' => 'Japan',
                'iso2' => 'JP',
                'iso3' => 'JPN',
                'calling_code' => 81,
                'calling_codes' => [81],
                'capital' => 'Tokyo',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia'
            ],
            [
                'name' => 'Jordan',
                'official_name' => 'Hashemite Kingdom of Jordan',
                'common_name' => 'Jordan',
                'short_name' => 'Jordan',
                'iso2' => 'JO',
                'iso3' => 'JOR',
                'calling_code' => 962,
                'calling_codes' => [962],
                'capital' => 'Amman',
                'region' => 'Asia',
                'subregion' => 'Western Asia'
            ],
            [
                'name' => 'Kazakhstan',
                'official_name' => 'Republic of Kazakhstan',
                'common_name' => 'Kazakhstan',
                'short_name' => 'Kazakhstan',
                'iso2' => 'KZ',
                'iso3' => 'KAZ',
                'calling_code' => 7,
                'calling_codes' => [7],
                'capital' => 'Astana',
                'region' => 'Asia',
                'subregion' => 'Central Asia'
            ],
            [
                'name' => 'Kuwait',
                'official_name' => 'State of Kuwait',
                'common_name' => 'Kuwait',
                'short_name' => 'Kuwait',
                'iso2' => 'KW',
                'iso3' => 'KWT',
                'calling_code' => 965,
                'calling_codes' => [965],
                'capital' => 'Kuwait City',
                'region' => 'Asia',
                'subregion' => 'Western Asia'
            ],
            [
                'name' => 'Kyrgyzstan',
                'official_name' => 'Kyrgyz Republic',
                'common_name' => 'Kyrgyzstan',
                'short_name' => 'Kyrgyzstan',
                'iso2' => 'KG',
                'iso3' => 'KGZ',
                'calling_code' => 996,
                'calling_codes' => [996],
                'capital' => 'Bishkek',
                'region' => 'Asia',
                'subregion' => 'Central Asia'
            ],
            [
                'name' => 'Laos',
                'official_name' => 'Lao People\'s Democratic Republic',
                'common_name' => 'Laos',
                'short_name' => 'Laos',
                'iso2' => 'LA',
                'iso3' => 'LAO',
                'calling_code' => 856,
                'calling_codes' => [856],
                'capital' => 'Vientiane',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia'
            ],
            [
                'name' => 'Lebanon',
                'official_name' => 'Lebanese Republic',
                'common_name' => 'Lebanon',
                'short_name' => 'Lebanon',
                'iso2' => 'LB',
                'iso3' => 'LBN',
                'calling_code' => 961,
                'calling_codes' => [961],
                'capital' => 'Beirut',
                'region' => 'Asia',
                'subregion' => 'Western Asia'
            ],
            [
                'name' => 'Malaysia',
                'official_name' => 'Malaysia',
                'common_name' => 'Malaysia',
                'short_name' => 'Malaysia',
                'iso2' => 'MY',
                'iso3' => 'MYS',
                'calling_code' => 60,
                'calling_codes' => [60],
                'capital' => 'Kuala Lumpur',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia'
            ],
            [
                'name' => 'Maldives',
                'official_name' => 'Republic of Maldives',
                'common_name' => 'Maldives',
                'short_name' => 'Maldives',
                'iso2' => 'MV',
                'iso3' => 'MDV',
                'calling_code' => 960,
                'calling_codes' => [960],
                'capital' => 'Malé',
                'region' => 'Asia',
                'subregion' => 'Southern Asia'
            ],
            [
                'name' => 'Mongolia',
                'official_name' => 'Mongolia',
                'common_name' => 'Mongolia',
                'short_name' => 'Mongolia',
                'iso2' => 'MN',
                'iso3' => 'MNG',
                'calling_code' => 976,
                'calling_codes' => [976],
                'capital' => 'Ulaanbaatar',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia'
            ],
            [
                'name' => 'Myanmar',
                'official_name' => 'Republic of the Union of Myanmar',
                'common_name' => 'Myanmar',
                'short_name' => 'Myanmar',
                'iso2' => 'MM',
                'iso3' => 'MMR',
                'calling_code' => 95,
                'calling_codes' => [95],
                'capital' => 'Naypyidaw',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia'
            ],
            [
                'name' => 'Nepal',
                'official_name' => 'Federal Democratic Republic of Nepal',
                'common_name' => 'Nepal',
                'short_name' => 'Nepal',
                'iso2' => 'NP',
                'iso3' => 'NPL',
                'calling_code' => 977,
                'calling_codes' => [977],
                'capital' => 'Kathmandu',
                'region' => 'Asia',
                'subregion' => 'Southern Asia'
            ],
            [
                'name' => 'North Korea',
                'official_name' => 'Democratic People\'s Republic of Korea',
                'common_name' => 'North Korea',
                'short_name' => 'N. Korea',
                'iso2' => 'KP',
                'iso3' => 'PRK',
                'calling_code' => 850,
                'calling_codes' => [850],
                'capital' => 'Pyongyang',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia'
            ],
            [
                'name' => 'Oman',
                'official_name' => 'Sultanate of Oman',
                'common_name' => 'Oman',
                'short_name' => 'Oman',
                'iso2' => 'OM',
                'iso3' => 'OMN',
                'calling_code' => 968,
                'calling_codes' => [968],
                'capital' => 'Muscat',
                'region' => 'Asia',
                'subregion' => 'Western Asia'
            ],
            [
                'name' => 'Pakistan',
                'official_name' => 'Islamic Republic of Pakistan',
                'common_name' => 'Pakistan',
                'short_name' => 'Pakistan',
                'iso2' => 'PK',
                'iso3' => 'PAK',
                'calling_code' => 92,
                'calling_codes' => [92],
                'capital' => 'Islamabad',
                'region' => 'Asia',
                'subregion' => 'Southern Asia'
            ],
            [
                'name' => 'Palestine',
                'official_name' => 'State of Palestine',
                'common_name' => 'Palestine',
                'short_name' => 'Palestine',
                'iso2' => 'PS',
                'iso3' => 'PSE',
                'calling_code' => 970,
                'calling_codes' => [970],
                'capital' => 'Ramallah',
                'region' => 'Asia',
                'subregion' => 'Western Asia'
            ],
            [
                'name' => 'Philippines',
                'official_name' => 'Republic of the Philippines',
                'common_name' => 'Philippines',
                'short_name' => 'Philippines',
                'iso2' => 'PH',
                'iso3' => 'PHL',
                'calling_code' => 63,
                'calling_codes' => [63],
                'capital' => 'Manila',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia'
            ],
            [
                'name' => 'Qatar',
                'official_name' => 'State of Qatar',
                'common_name' => 'Qatar',
                'short_name' => 'Qatar',
                'iso2' => 'QA',
                'iso3' => 'QAT',
                'calling_code' => 974,
                'calling_codes' => [974],
                'capital' => 'Doha',
                'region' => 'Asia',
                'subregion' => 'Western Asia'
            ],
            [
                'name' => 'Saudi Arabia',
                'official_name' => 'Kingdom of Saudi Arabia',
                'common_name' => 'Saudi Arabia',
                'short_name' => 'Saudi Arabia',
                'iso2' => 'SA',
                'iso3' => 'SAU',
                'calling_code' => 966,
                'calling_codes' => [966],
                'capital' => 'Riyadh',
                'region' => 'Asia',
                'subregion' => 'Western Asia'
            ],
            [
                'name' => 'Singapore',
                'official_name' => 'Republic of Singapore',
                'common_name' => 'Singapore',
                'short_name' => 'Singapore',
                'iso2' => 'SG',
                'iso3' => 'SGP',
                'calling_code' => 65,
                'calling_codes' => [65],
                'capital' => 'Singapore',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia'
            ],
            [
                'name' => 'South Korea',
                'official_name' => 'Republic of Korea',
                'common_name' => 'South Korea',
                'short_name' => 'S. Korea',
                'iso2' => 'KR',
                'iso3' => 'KOR',
                'calling_code' => 82,
                'calling_codes' => [82],
                'capital' => 'Seoul',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia'
            ],
            [
                'name' => 'Sri Lanka',
                'official_name' => 'Democratic Socialist Republic of Sri Lanka',
                'common_name' => 'Sri Lanka',
                'short_name' => 'Sri Lanka',
                'iso2' => 'LK',
                'iso3' => 'LKA',
                'calling_code' => 94,
                'calling_codes' => [94],
                'capital' => 'Sri Jayawardenepura Kotte',
                'region' => 'Asia',
                'subregion' => 'Southern Asia'
            ],
            [
                'name' => 'Syria',
                'official_name' => 'Syrian Arab Republic',
                'common_name' => 'Syria',
                'short_name' => 'Syria',
                'iso2' => 'SY',
                'iso3' => 'SYR',
                'calling_code' => 963,
                'calling_codes' => [963],
                'capital' => 'Damascus',
                'region' => 'Asia',
                'subregion' => 'Western Asia'
            ],
            [
                'name' => 'Taiwan',
                'official_name' => 'Republic of China (Taiwan)',
                'common_name' => 'Taiwan',
                'short_name' => 'Taiwan',
                'iso2' => 'TW',
                'iso3' => 'TWN',
                'calling_code' => 886,
                'calling_codes' => [886],
                'capital' => 'Taipei',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia'
            ],
            [
                'name' => 'Tajikistan',
                'official_name' => 'Republic of Tajikistan',
                'common_name' => 'Tajikistan',
                'short_name' => 'Tajikistan',
                'iso2' => 'TJ',
                'iso3' => 'TJK',
                'calling_code' => 992,
                'calling_codes' => [992],
                'capital' => 'Dushanbe',
                'region' => 'Asia',
                'subregion' => 'Central Asia'
            ],
            [
                'name' => 'Thailand',
                'official_name' => 'Kingdom of Thailand',
                'common_name' => 'Thailand',
                'short_name' => 'Thailand',
                'iso2' => 'TH',
                'iso3' => 'THA',
                'calling_code' => 66,
                'calling_codes' => [66],
                'capital' => 'Bangkok',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia'
            ],
            [
                'name' => 'Timor-Leste',
                'official_name' => 'Democratic Republic of Timor-Leste',
                'common_name' => 'East Timor',
                'short_name' => 'Timor-Leste',
                'iso2' => 'TL',
                'iso3' => 'TLS',
                'calling_code' => 670,
                'calling_codes' => [670],
                'capital' => 'Dili',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia'
            ],
            [
                'name' => 'Turkey',
                'official_name' => 'Republic of Turkey',
                'common_name' => 'Turkey',
                'short_name' => 'Turkey',
                'iso2' => 'TR',
                'iso3' => 'TUR',
                'calling_code' => 90,
                'calling_codes' => [90],
                'capital' => 'Ankara',
                'region' => 'Asia',
                'subregion' => 'Western Asia'
            ],
            [
                'name' => 'Turkmenistan',
                'official_name' => 'Turkmenistan',
                'common_name' => 'Turkmenistan',
                'short_name' => 'Turkmenistan',
                'iso2' => 'TM',
                'iso3' => 'TKM',
                'calling_code' => 993,
                'calling_codes' => [993],
                'capital' => 'Ashgabat',
                'region' => 'Asia',
                'subregion' => 'Central Asia'
            ],
            [
                'name' => 'United Arab Emirates',
                'official_name' => 'United Arab Emirates',
                'common_name' => 'United Arab Emirates',
                'short_name' => 'UAE',
                'iso2' => 'AE',
                'iso3' => 'ARE',
                'calling_code' => 971,
                'calling_codes' => [971],
                'capital' => 'Abu Dhabi',
                'region' => 'Asia',
                'subregion' => 'Western Asia'
            ],
            [
                'name' => 'Uzbekistan',
                'official_name' => 'Republic of Uzbekistan',
                'common_name' => 'Uzbekistan',
                'short_name' => 'Uzbekistan',
                'iso2' => 'UZ',
                'iso3' => 'UZB',
                'calling_code' => 998,
                'calling_codes' => [998],
                'capital' => 'Tashkent',
                'region' => 'Asia',
                'subregion' => 'Central Asia'
            ],
            [
                'name' => 'Vietnam',
                'official_name' => 'Socialist Republic of Vietnam',
                'common_name' => 'Vietnam',
                'short_name' => 'Vietnam',
                'iso2' => 'VN',
                'iso3' => 'VNM',
                'calling_code' => 84,
                'calling_codes' => [84],
                'capital' => 'Hanoi',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia'
            ],
            [
                'name' => 'Yemen',
                'official_name' => 'Republic of Yemen',
                'common_name' => 'Yemen',
                'short_name' => 'Yemen',
                'iso2' => 'YE',
                'iso3' => 'YEM',
                'calling_code' => 967,
                'calling_codes' => [967],
                'capital' => 'Sana\'a',
                'region' => 'Asia',
                'subregion' => 'Western Asia'
            ],

            // Europe
            [
                'name' => 'Albania',
                'official_name' => 'Republic of Albania',
                'common_name' => 'Albania',
                'short_name' => 'Albania',
                'iso2' => 'AL',
                'iso3' => 'ALB',
                'calling_code' => 355,
                'calling_codes' => [355],
                'capital' => 'Tirana',
                'region' => 'Europe',
                'subregion' => 'Southern Europe'
            ],
            [
                'name' => 'Andorra',
                'official_name' => 'Principality of Andorra',
                'common_name' => 'Andorra',
                'short_name' => 'Andorra',
                'iso2' => 'AD',
                'iso3' => 'AND',
                'calling_code' => 376,
                'calling_codes' => [376],
                'capital' => 'Andorra la Vella',
                'region' => 'Europe',
                'subregion' => 'Southern Europe'
            ],
            [
                'name' => 'Austria',
                'official_name' => 'Republic of Austria',
                'common_name' => 'Austria',
                'short_name' => 'Austria',
                'iso2' => 'AT',
                'iso3' => 'AUT',
                'calling_code' => 43,
                'calling_codes' => [43],
                'capital' => 'Vienna',
                'region' => 'Europe',
                'subregion' => 'Western Europe'
            ],
            [
                'name' => 'Belarus',
                'official_name' => 'Republic of Belarus',
                'common_name' => 'Belarus',
                'short_name' => 'Belarus',
                'iso2' => 'BY',
                'iso3' => 'BLR',
                'calling_code' => 375,
                'calling_codes' => [375],
                'capital' => 'Minsk',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe'
            ],
            [
                'name' => 'Belgium',
                'official_name' => 'Kingdom of Belgium',
                'common_name' => 'Belgium',
                'short_name' => 'Belgium',
                'iso2' => 'BE',
                'iso3' => 'BEL',
                'calling_code' => 32,
                'calling_codes' => [32],
                'capital' => 'Brussels',
                'region' => 'Europe',
                'subregion' => 'Western Europe'
            ],
            [
                'name' => 'Bosnia and Herzegovina',
                'official_name' => 'Bosnia and Herzegovina',
                'common_name' => 'Bosnia and Herzegovina',
                'short_name' => 'Bosnia',
                'iso2' => 'BA',
                'iso3' => 'BIH',
                'calling_code' => 387,
                'calling_codes' => [387],
                'capital' => 'Sarajevo',
                'region' => 'Europe',
                'subregion' => 'Southern Europe'
            ],
            [
                'name' => 'Bulgaria',
                'official_name' => 'Republic of Bulgaria',
                'common_name' => 'Bulgaria',
                'short_name' => 'Bulgaria',
                'iso2' => 'BG',
                'iso3' => 'BGR',
                'calling_code' => 359,
                'calling_codes' => [359],
                'capital' => 'Sofia',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe'
            ],
            [
                'name' => 'Croatia',
                'official_name' => 'Republic of Croatia',
                'common_name' => 'Croatia',
                'short_name' => 'Croatia',
                'iso2' => 'HR',
                'iso3' => 'HRV',
                'calling_code' => 385,
                'calling_codes' => [385],
                'capital' => 'Zagreb',
                'region' => 'Europe',
                'subregion' => 'Southern Europe'
            ],
            [
                'name' => 'Czech Republic',
                'official_name' => 'Czech Republic',
                'common_name' => 'Czech Republic',
                'short_name' => 'Czechia',
                'iso2' => 'CZ',
                'iso3' => 'CZE',
                'calling_code' => 420,
                'calling_codes' => [420],
                'capital' => 'Prague',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe'
            ],
            [
                'name' => 'Denmark',
                'official_name' => 'Kingdom of Denmark',
                'common_name' => 'Denmark',
                'short_name' => 'Denmark',
                'iso2' => 'DK',
                'iso3' => 'DNK',
                'calling_code' => 45,
                'calling_codes' => [45],
                'capital' => 'Copenhagen',
                'region' => 'Europe',
                'subregion' => 'Northern Europe'
            ],
            [
                'name' => 'Estonia',
                'official_name' => 'Republic of Estonia',
                'common_name' => 'Estonia',
                'short_name' => 'Estonia',
                'iso2' => 'EE',
                'iso3' => 'EST',
                'calling_code' => 372,
                'calling_codes' => [372],
                'capital' => 'Tallinn',
                'region' => 'Europe',
                'subregion' => 'Northern Europe'
            ],
            [
                'name' => 'Finland',
                'official_name' => 'Republic of Finland',
                'common_name' => 'Finland',
                'short_name' => 'Finland',
                'iso2' => 'FI',
                'iso3' => 'FIN',
                'calling_code' => 358,
                'calling_codes' => [358],
                'capital' => 'Helsinki',
                'region' => 'Europe',
                'subregion' => 'Northern Europe'
            ],
            [
                'name' => 'France',
                'official_name' => 'French Republic',
                'common_name' => 'France',
                'short_name' => 'France',
                'iso2' => 'FR',
                'iso3' => 'FRA',
                'calling_code' => 33,
                'calling_codes' => [33],
                'capital' => 'Paris',
                'region' => 'Europe',
                'subregion' => 'Western Europe'
            ],
            [
                'name' => 'Germany',
                'official_name' => 'Federal Republic of Germany',
                'common_name' => 'Germany',
                'short_name' => 'Germany',
                'iso2' => 'DE',
                'iso3' => 'DEU',
                'calling_code' => 49,
                'calling_codes' => [49],
                'capital' => 'Berlin',
                'region' => 'Europe',
                'subregion' => 'Western Europe'
            ],
            [
                'name' => 'Greece',
                'official_name' => 'Hellenic Republic',
                'common_name' => 'Greece',
                'short_name' => 'Greece',
                'iso2' => 'GR',
                'iso3' => 'GRC',
                'calling_code' => 30,
                'calling_codes' => [30],
                'capital' => 'Athens',
                'region' => 'Europe',
                'subregion' => 'Southern Europe'
            ],
            [
                'name' => 'Hungary',
                'official_name' => 'Hungary',
                'common_name' => 'Hungary',
                'short_name' => 'Hungary',
                'iso2' => 'HU',
                'iso3' => 'HUN',
                'calling_code' => 36,
                'calling_codes' => [36],
                'capital' => 'Budapest',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe'
            ],
            [
                'name' => 'Iceland',
                'official_name' => 'Iceland',
                'common_name' => 'Iceland',
                'short_name' => 'Iceland',
                'iso2' => 'IS',
                'iso3' => 'ISL',
                'calling_code' => 354,
                'calling_codes' => [354],
                'capital' => 'Reykjavik',
                'region' => 'Europe',
                'subregion' => 'Northern Europe'
            ],
            [
                'name' => 'Ireland',
                'official_name' => 'Republic of Ireland',
                'common_name' => 'Ireland',
                'short_name' => 'Ireland',
                'iso2' => 'IE',
                'iso3' => 'IRL',
                'calling_code' => 353,
                'calling_codes' => [353],
                'capital' => 'Dublin',
                'region' => 'Europe',
                'subregion' => 'Northern Europe'
            ],
            [
                'name' => 'Italy',
                'official_name' => 'Italian Republic',
                'common_name' => 'Italy',
                'short_name' => 'Italy',
                'iso2' => 'IT',
                'iso3' => 'ITA',
                'calling_code' => 39,
                'calling_codes' => [39],
                'capital' => 'Rome',
                'region' => 'Europe',
                'subregion' => 'Southern Europe'
            ],
            [
                'name' => 'Kosovo',
                'official_name' => 'Republic of Kosovo',
                'common_name' => 'Kosovo',
                'short_name' => 'Kosovo',
                'iso2' => 'XK',
                'iso3' => 'XKX',
                'calling_code' => 383,
                'calling_codes' => [383],
                'capital' => 'Pristina',
                'region' => 'Europe',
                'subregion' => 'Southern Europe'
            ],
            [
                'name' => 'Latvia',
                'official_name' => 'Republic of Latvia',
                'common_name' => 'Latvia',
                'short_name' => 'Latvia',
                'iso2' => 'LV',
                'iso3' => 'LVA',
                'calling_code' => 371,
                'calling_codes' => [371],
                'capital' => 'Riga',
                'region' => 'Europe',
                'subregion' => 'Northern Europe'
            ],
            [
                'name' => 'Liechtenstein',
                'official_name' => 'Principality of Liechtenstein',
                'common_name' => 'Liechtenstein',
                'short_name' => 'Liechtenstein',
                'iso2' => 'LI',
                'iso3' => 'LIE',
                'calling_code' => 423,
                'calling_codes' => [423],
                'capital' => 'Vaduz',
                'region' => 'Europe',
                'subregion' => 'Western Europe'
            ],
            [
                'name' => 'Lithuania',
                'official_name' => 'Republic of Lithuania',
                'common_name' => 'Lithuania',
                'short_name' => 'Lithuania',
                'iso2' => 'LT',
                'iso3' => 'LTU',
                'calling_code' => 370,
                'calling_codes' => [370],
                'capital' => 'Vilnius',
                'region' => 'Europe',
                'subregion' => 'Northern Europe'
            ],
            [
                'name' => 'Luxembourg',
                'official_name' => 'Grand Duchy of Luxembourg',
                'common_name' => 'Luxembourg',
                'short_name' => 'Luxembourg',
                'iso2' => 'LU',
                'iso3' => 'LUX',
                'calling_code' => 352,
                'calling_codes' => [352],
                'capital' => 'Luxembourg',
                'region' => 'Europe',
                'subregion' => 'Western Europe'
            ],
            [
                'name' => 'Malta',
                'official_name' => 'Republic of Malta',
                'common_name' => 'Malta',
                'short_name' => 'Malta',
                'iso2' => 'MT',
                'iso3' => 'MLT',
                'calling_code' => 356,
                'calling_codes' => [356],
                'capital' => 'Valletta',
                'region' => 'Europe',
                'subregion' => 'Southern Europe'
            ],
            [
                'name' => 'Moldova',
                'official_name' => 'Republic of Moldova',
                'common_name' => 'Moldova',
                'short_name' => 'Moldova',
                'iso2' => 'MD',
                'iso3' => 'MDA',
                'calling_code' => 373,
                'calling_codes' => [373],
                'capital' => 'Chișinău',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe'
            ],
            [
                'name' => 'Monaco',
                'official_name' => 'Principality of Monaco',
                'common_name' => 'Monaco',
                'short_name' => 'Monaco',
                'iso2' => 'MC',
                'iso3' => 'MCO',
                'calling_code' => 377,
                'calling_codes' => [377],
                'capital' => 'Monaco',
                'region' => 'Europe',
                'subregion' => 'Western Europe'
            ],
            [
                'name' => 'Montenegro',
                'official_name' => 'Montenegro',
                'common_name' => 'Montenegro',
                'short_name' => 'Montenegro',
                'iso2' => 'ME',
                'iso3' => 'MNE',
                'calling_code' => 382,
                'calling_codes' => [382],
                'capital' => 'Podgorica',
                'region' => 'Europe',
                'subregion' => 'Southern Europe'
            ],
            [
                'name' => 'Netherlands',
                'official_name' => 'Kingdom of the Netherlands',
                'common_name' => 'Netherlands',
                'short_name' => 'Netherlands',
                'iso2' => 'NL',
                'iso3' => 'NLD',
                'calling_code' => 31,
                'calling_codes' => [31],
                'capital' => 'Amsterdam',
                'region' => 'Europe',
                'subregion' => 'Western Europe'
            ],
            [
                'name' => 'North Macedonia',
                'official_name' => 'Republic of North Macedonia',
                'common_name' => 'North Macedonia',
                'short_name' => 'N. Macedonia',
                'iso2' => 'MK',
                'iso3' => 'MKD',
                'calling_code' => 389,
                'calling_codes' => [389],
                'capital' => 'Skopje',
                'region' => 'Europe',
                'subregion' => 'Southern Europe'
            ],
            [
                'name' => 'Norway',
                'official_name' => 'Kingdom of Norway',
                'common_name' => 'Norway',
                'short_name' => 'Norway',
                'iso2' => 'NO',
                'iso3' => 'NOR',
                'calling_code' => 47,
                'calling_codes' => [47],
                'capital' => 'Oslo',
                'region' => 'Europe',
                'subregion' => 'Northern Europe'
            ],
            [
                'name' => 'Poland',
                'official_name' => 'Republic of Poland',
                'common_name' => 'Poland',
                'short_name' => 'Poland',
                'iso2' => 'PL',
                'iso3' => 'POL',
                'calling_code' => 48,
                'calling_codes' => [48],
                'capital' => 'Warsaw',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe'
            ],
            [
                'name' => 'Portugal',
                'official_name' => 'Portuguese Republic',
                'common_name' => 'Portugal',
                'short_name' => 'Portugal',
                'iso2' => 'PT',
                'iso3' => 'PRT',
                'calling_code' => 351,
                'calling_codes' => [351],
                'capital' => 'Lisbon',
                'region' => 'Europe',
                'subregion' => 'Southern Europe'
            ],
            [
                'name' => 'Romania',
                'official_name' => 'Romania',
                'common_name' => 'Romania',
                'short_name' => 'Romania',
                'iso2' => 'RO',
                'iso3' => 'ROU',
                'calling_code' => 40,
                'calling_codes' => [40],
                'capital' => 'Bucharest',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe'
            ],
            //...
        ];
    }
}